CREATE TABLE IF NOT EXISTS usuarios (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS gastos (
    id SERIAL PRIMARY KEY,
    descripcion TEXT NOT NULL,
    monto DECIMAL(10,2) NOT NULL,
    fecha DATE DEFAULT CURRENT_DATE
);


CREATE TABLE IF NOT EXISTS deudores (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    descripcion TEXT NOT NULL,
    monto DECIMAL(10,2) NOT NULL,
    fecha DATE DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS caja_inversion (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    descripcion TEXT NOT NULL,
    monto DECIMAL(10,2) NOT NULL,
    fecha DATE DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS caja_reposicion_stock (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    descripcion TEXT NOT NULL,
    monto DECIMAL(10,2) NOT NULL,
    fecha DATE DEFAULT CURRENT_DATE
);

CREATE TABLE productos (
	id SERIAL PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL,
	precio DECIMAL(10,2) NOT NULL,
	stock INTEGER NOT NULL,
	fecha DATE DEFAULT CURRENT_DATE
);


CREATE TABLE ventas (
	id SERIAL PRIMARY KEY,
	nombre VARCHAR(50) NOT NULL,
	precio DECIMAL(10,2) NOT NULL,
	producto_id INTEGER REFERENCES productos(id),
	cantidad INTEGER DEFAULT 1,
	fecha DATE DEFAULT CURRENT_DATE
);